<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Fisiofit.BuildingBlocks/Fisiofit.BuildingBlocks.csproj" />
    <ProjectReference Include="../../Fisiofit.ModuleContracts/Fisiofit.ModuleContracts.csproj" />
  </ItemGroup>
</Project>
