// <auto-generated />
using System;
using Fisiofit.Modules.Registry.Organization.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fisiofit.Modules.Registry.Organization.Infrastructure.Migrations.Organization
{
    [DbContext(typeof(OrganizationDbContext))]
    [Migration("20260917010742_Organization_InitialUnitBaseline")]
    partial class Organization_InitialUnitBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("organization")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fisiofit.Modules.Registry.Organization.Domain.Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id")
                        .HasName("pk_clinic");

                    b.ToTable("clinic", "organization", t =>
                        {
                            t.HasCheckConstraint("ck_clinic__status", "status IN ('ACTIVE', 'INACTIVE')");
                        });
                });

            modelBuilder.Entity("Fisiofit.Modules.Registry.Organization.Domain.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinic_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_unit");

                    b.HasIndex("ClinicId")
                        .HasDatabaseName("ix_unit__clinic_id");

                    b.ToTable("unit", "organization", t =>
                        {
                            t.HasCheckConstraint("ck_unit__status", "status IN ('ACTIVE', 'INACTIVE')");
                        });
                });

            modelBuilder.Entity("Fisiofit.Modules.Registry.Organization.Domain.Unit", b =>
                {
                    b.HasOne("Fisiofit.Modules.Registry.Organization.Domain.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_unit__clinic");

                    b.Navigation("Clinic");
                });
#pragma warning restore 612, 618
        }
    }
}
