<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../Fisiofit.BuildingBlocks/Fisiofit.BuildingBlocks.csproj" />
    <ProjectReference Include="../Fisiofit.ModuleContracts/Fisiofit.ModuleContracts.csproj" />
    <ProjectReference Include="../Modules/Fisiofit.Modules.Access/Fisiofit.Modules.Access.csproj" />
    <ProjectReference Include="../Modules/Fisiofit.Modules.Registry/Fisiofit.Modules.Registry.csproj" />
    <ProjectReference Include="../Modules/Fisiofit.Modules.Crm/Fisiofit.Modules.Crm.csproj" />
    <ProjectReference Include="../Modules/Fisiofit.Modules.Operations/Fisiofit.Modules.Operations.csproj" />
    <ProjectReference Include="../Modules/Fisiofit.Modules.Clinical/Fisiofit.Modules.Clinical.csproj" />
    <ProjectReference Include="../Modules/Fisiofit.Modules.Revenue/Fisiofit.Modules.Revenue.csproj" />
    <ProjectReference Include="../Modules/Fisiofit.Modules.Communication/Fisiofit.Modules.Communication.csproj" />
    <ProjectReference Include="../Modules/Fisiofit.Modules.Documents/Fisiofit.Modules.Documents.csproj" />
    <ProjectReference Include="../Modules/Fisiofit.Modules.Audit/Fisiofit.Modules.Audit.csproj" />
    <ProjectReference Include="../Modules/Fisiofit.Modules.Reports/Fisiofit.Modules.Reports.csproj" />
  </ItemGroup>
</Project>
