// <auto-generated />
using System;
using Fisiofit.Modules.Registry.People.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fisiofit.Modules.Registry.People.Infrastructure.Migrations.People
{
    [DbContext(typeof(PeopleDbContext))]
    partial class PeopleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("people")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fisiofit.Modules.Registry.People.Domain.ContactPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("area_code");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("country_code");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("kind");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("normalized_value");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("number");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_contact_point");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ux_contact_point__active_primary_phone")
                        .HasFilter("kind = 'PHONE' AND is_primary = TRUE AND status = 'ACTIVE'");

                    b.ToTable("contact_point", "people", t =>
                        {
                            t.HasCheckConstraint("ck_contact_point__kind", "kind = 'PHONE'");

                            t.HasCheckConstraint("ck_contact_point__status", "status IN ('ACTIVE', 'INACTIVE')");
                        });
                });

            modelBuilder.Entity("Fisiofit.Modules.Registry.People.Domain.PeopleCommandReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CallerContext")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("caller_context");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operation_key");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_command_receipt");

                    b.HasIndex("CallerContext", "Operation", "OperationKey")
                        .IsUnique()
                        .HasDatabaseName("ux_people_command_receipt__scope");

                    b.ToTable("command_receipt", "people", t =>
                        {
                            t.HasCheckConstraint("ck_people_command_receipt__state", "state = 'COMPLETED'");
                        });
                });

            modelBuilder.Entity("Fisiofit.Modules.Registry.People.Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("CpfNormalized")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf_normalized");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("RecordState")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("record_state");

                    b.HasKey("Id")
                        .HasName("pk_person");

                    b.HasIndex("CpfNormalized")
                        .IsUnique()
                        .HasDatabaseName("ux_person__cpf_normalized")
                        .HasFilter("cpf_normalized IS NOT NULL");

                    b.ToTable("person", "people", t =>
                        {
                            t.HasCheckConstraint("ck_person__record_state", "record_state IN ('CURRENT', 'INACTIVE', 'MERGED_ALIAS')");
                        });
                });

            modelBuilder.Entity("Fisiofit.Modules.Registry.People.Domain.ContactPoint", b =>
                {
                    b.HasOne("Fisiofit.Modules.Registry.People.Domain.Person", "Person")
                        .WithMany("ContactPoints")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contact_point__person");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Fisiofit.Modules.Registry.People.Domain.Person", b =>
                {
                    b.Navigation("ContactPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
