// <auto-generated />
using System;
using Fisiofit.Modules.Registry.Patients.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fisiofit.Modules.Registry.Patients.Infrastructure.Migrations.Patients
{
    [DbContext(typeof(PatientsDbContext))]
    [Migration("20260918180545_Patients_InitialPatientRegistrationSlice")]
    partial class Patients_InitialPatientRegistrationSlice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("patients")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fisiofit.Modules.Registry.Patients.Domain.PatientCommandReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResultStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result_status");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_command_receipt");

                    b.HasIndex("WorkflowId")
                        .IsUnique()
                        .HasDatabaseName("ux_patient_command_receipt__workflow_id");

                    b.HasIndex("ActorId", "Operation", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_patient_command_receipt__scope");

                    b.ToTable("command_receipt", "patients", t =>
                        {
                            t.HasCheckConstraint("ck_patient_command_receipt__state", "state IN ('STARTED', 'PERSON_CONFIRMED', 'COMPLETED')");
                        });
                });

            modelBuilder.Entity("Fisiofit.Modules.Registry.Patients.Domain.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdministrativeStatus")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("administrative_status");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("PrimaryUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_unit_id");

                    b.Property<DateOnly>("RelationshipStartedOn")
                        .HasColumnType("date")
                        .HasColumnName("relationship_started_on");

                    b.HasKey("Id")
                        .HasName("pk_patient_profile");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ux_patient_profile__person_id");

                    b.HasIndex("PrimaryUnitId")
                        .HasDatabaseName("ix_patient_profile__primary_unit_id");

                    b.ToTable("patient_profile", "patients", t =>
                        {
                            t.HasCheckConstraint("ck_patient_profile__administrative_status", "administrative_status IN ('ACTIVE', 'INACTIVE')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
