// <auto-generated />
using System;
using Fisiofit.Modules.Registry.Patients.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fisiofit.Modules.Registry.Patients.Infrastructure.Migrations.Patients
{
    [DbContext(typeof(PatientsDbContext))]
    partial class PatientsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("patients")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fisiofit.Modules.Registry.Patients.Domain.PatientCommandReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResultStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result_status");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_command_receipt");

                    b.HasIndex("WorkflowId")
                        .IsUnique()
                        .HasDatabaseName("ux_patient_command_receipt__workflow_id");

                    b.HasIndex("ActorId", "Operation", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_patient_command_receipt__scope");

                    b.ToTable("command_receipt", "patients", t =>
                        {
                            t.HasCheckConstraint("ck_patient_command_receipt__state", "state IN ('STARTED', 'PERSON_CONFIRMED', 'COMPLETED')");
                        });
                });

            modelBuilder.Entity("Fisiofit.Modules.Registry.Patients.Domain.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdministrativeStatus")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("administrative_status");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("PrimaryUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_unit_id");

                    b.Property<DateOnly>("RelationshipStartedOn")
                        .HasColumnType("date")
                        .HasColumnName("relationship_started_on");

                    b.HasKey("Id")
                        .HasName("pk_patient_profile");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ux_patient_profile__person_id");

                    b.HasIndex("PrimaryUnitId")
                        .HasDatabaseName("ix_patient_profile__primary_unit_id");

                    b.ToTable("patient_profile", "patients", t =>
                        {
                            t.HasCheckConstraint("ck_patient_profile__administrative_status", "administrative_status IN ('ACTIVE', 'INACTIVE')");
                        });
                });
            modelBuilder.Entity("Fisiofit.Modules.Registry.Patients.Domain.GuardianLink", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("guardian_link_id");
                    b.Property<Guid>("CreatedByActorId").HasColumnType("uuid").HasColumnName("created_by_actor_id");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<Guid?>("EndedByActorId").HasColumnType("uuid").HasColumnName("ended_by_actor_id");
                    b.Property<DateTimeOffset?>("EndedAt").HasColumnType("timestamp with time zone").HasColumnName("ended_at");
                    b.Property<DateOnly>("EffectiveFrom").HasColumnType("date").HasColumnName("effective_from");
                    b.Property<DateOnly?>("EffectiveTo").HasColumnType("date").HasColumnName("effective_to");
                    b.Property<Guid>("GuardianPersonId").HasColumnType("uuid").HasColumnName("guardian_person_id");
                    b.Property<bool>("IsPrimary").HasColumnType("boolean").HasColumnName("is_primary_legal_guardian");
                    b.Property<Guid>("PatientProfileId").HasColumnType("uuid").HasColumnName("patient_profile_id");
                    b.Property<int>("Version").HasColumnType("integer").HasColumnName("version");
                    b.HasKey("Id").HasName("pk_guardian_link");
                    b.HasIndex("GuardianPersonId").HasDatabaseName("ix_guardian_link__guardian_person_id");
                    b.HasIndex("PatientProfileId", "EffectiveFrom", "EffectiveTo").HasDatabaseName("ix_guardian_link__patient_period");
                    b.HasIndex("PatientProfileId", "GuardianPersonId", "EffectiveFrom").IsUnique().HasDatabaseName("ux_guardian_link__patient_guardian_start");
                    b.HasIndex("PatientProfileId", "IsPrimary").HasFilter("is_primary_legal_guardian = TRUE AND effective_to IS NULL").HasDatabaseName("ix_guardian_link__open_primary");
                    b.ToTable("guardian_link", "patients", t => { t.HasCheckConstraint("ck_guardian_link__period", "effective_to IS NULL OR effective_to > effective_from"); t.HasCheckConstraint("ck_guardian_link__version", "version > 0"); t.HasCheckConstraint("ck_guardian_link__end_evidence", "(ended_at IS NULL AND ended_by_actor_id IS NULL) OR (ended_at IS NOT NULL AND ended_by_actor_id IS NOT NULL)"); });
                });

            modelBuilder.Entity("Fisiofit.Modules.Registry.Patients.Domain.GuardianLink", b =>
                {
                    b.HasOne("Fisiofit.Modules.Registry.Patients.Domain.PatientProfile", null).WithMany().HasForeignKey("PatientProfileId").OnDelete(DeleteBehavior.Restrict).IsRequired().HasConstraintName("fk_guardian_link__patient_profile");
                });
#pragma warning restore 612, 618
        }
    }
}
